### ISSUE TITLE
Error running `npm install microdrop-3.0 -g` on Windows

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#3]
# Steps to reproduce

### Method 1

 1. Download [microdrop-npm-minimal-test.zip](https://github.com/sci-bots/microdrop-3.0/files/1519451/microdrop-npm-minimal-test.zip) and unzip to `microdrop-npm-minimal-test.yaml` containing:

      ```yaml
      name: npm-test
      channels:
      - sci-bots
      - microdrop-plugins
      - wheeler-microfluidics
      - conda-forge
      - defaults
      dependencies:
      - vs2015_runtime=14.0.25420=0
      - nodejs=8.2.1=0
      ```

 2. Run:

        conda env create --file .\microdrop-npm-minimal-test.yaml

### Method 2

 1. Create a new Conda environment including only `nodejs`:

        conda create -n npm-test nodejs
 2. Activate environment

        activate npm-test

## II. Try to install `microdrop-3.0` package using `npm`:

        npm install microdrop-3.0 -g

# Observed behaviour

A compile error happens during compilation of `leveldown` package.

# Workaround

Install `windows-build-tools`:

    npm install --production -g windows-build-tools
